config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  # SIMPLE ROUTES FOR APP>VIWES>PASSWORD_RESET
  get 'password_resets/new'
  get 'password_resets/edit'

  # SIMPLE ROUTES FOR APP>VIEWS>USERS
  get 'users/new'
  get 'users/dashboard'
  get 'users/show'
  get 'users/index'

  # SIMPLE ROUTES FOR APP>VIEWS>REGISTER
  get  '/register',  to: 'users#new'
  post '/register',  to: 'users#create'

  # SIMPLE ROUTES FOR APP>VIEWS>LOGIN AND APP>VIEWS>LOGOUT
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # SIMPLE ROUTES FOR APP>VIEWS>SESSION
  get 'sessions/new'

  # SIMPLE ROUTES FOR APP>VIEWS>SCRAPS
  get 'scraps/index'

  # ROUTES TO SHOW APP>VIEWS>STATIC_PAGES ERB FILES
  get 'static_pages/home'
  get 'static_pages/data_tables'
  get 'static_pages/contact'
  get 'static_pages/ourvalues'
  get 'static_pages/AKL'
  get 'static_pages/rak'
  get 'static_pages/service'
  get 'static_pages/about'
  get 'static_pages/visitus'
  get 'static_pages/scrap_project'

  # RESOURCEFUL ROUTES
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :operatings,    :index, :show, :new, :create, :destroy
  resources :services,      :index, :show, :new, :create, :destroy
  resources :news,          :index, :show, :destroy
  resources :scraps,        :index, :show, :new, :create, :destroy
  resources :locations,     :index, :show, :new, :create, :destroy
  resources :employees,     :index, :show, :new, :create, :destroy
  resources :vessels,       :index
  resources :items,         :index, :show, :new, :create, :destroy
  resources :offshores,     :index, :show, :new, :create, :destroy
  resources :projects,      :index, :show, :new, :create, :destroy
  resources :contracts,     :index, :show, :new, :create, :destroy
  resources :companies,     :index, :show, :new, :create, :destroy
  resources :users
  resources :tests
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # ROUTES TO SHOW EACH OF THE QUERIES ERB VIEW:
  get 'queries/query1', to: 'queries#query1'
  get 'queries/query2', to: 'queries#query2'
  get 'queries/query4', to: 'queries#query4'
  get 'queries/query5', to: 'queries#query5'
  get 'queries/query6', to: 'queries#query6'
  get 'queries/query7', to: 'queries#query7'
  get 'queries/query8', to: 'queries#query8'
  get 'queries/query10', to: 'queries#query10'
  get 'queries/query12', to: 'queries#query12'
  get 'queries/project', to: 'queries#project'
  # ROUTES TO PROCESS THE FORM IN EACH OF THE QUERIES ERB VIEW
  post 'queries/query1'
  post 'queries/query2'
  post 'queries/query4'
  post 'queries/query5'
  post 'queries/query6'
  post 'queries/query7'
  post 'queries/query8'
  post 'queries/query10'
  post 'queries/query12'
  post 'queries/project'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def data_tables
  end
  
  def data
  end

  def services
  end

  def akl
  end
  
  def rak4
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/AKL.html.erb
<h1>AKL</h1>

  <h4 style="color: #00B4E4">Archer Knight was set up in 2016 by David Sheret and Mike Watson.</h4>
  <h4>Both have over 20 years’ experience in the subsea oil and gas sector in senior management roles covering commercial, business development, market intelligence and communications.</h4>
  <h4>The company has two main service lines; <font style="color: #00B4E4"> call off services</font> (business development, commercial,driving,engineering HSEQ, ROV, security & marine assets management and supply chain $ logistics) and <font style="color: #00B4E4">microeconomic reporting</font> on subsea sector - subscription and commisioned.</h4>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

  <div class='col-md-4'>
  </div>
  <div class="col-md-2">
    <div id="contact">
      <h3><i class="fa fa-mobile" aria-hidden="true"></i> 07718 312121<br>
      <i class="fa fa-mobile" aria-hidden="true"></i>  07802 578334<br>
      <i class="fa fa-phone" aria-hidden="true"></i>01224 358694</h3><br>

    </div>
  </div>

  <div class='col-md-4'><br>
    <h3><i class="fa fa-envelope" aria-hidden="true"></i> info@archerknight.co.uk</h3>
  </div>
  <div class='col-md-2'>
  </div>

app/views/static_pages/data.html.erb
jjjjj

app/views/static_pages/data_tables.html.erb
<h1>Data Tables</h1>
require_login!
  <nav>
    <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "Asset",  items_path %></li><hr>
        <li><%= link_to "Contracts",  contracts_path %></li><hr>
        <li><%= link_to "Employees", employees_path %></li><hr>
        <li><%= link_to "Locations", locations_path %></li><hr>
        <li><%= link_to "Offshores Fields",  offshores_path %></li><hr>
        <li><%= link_to "Operating companies",  operatings_path %></li><hr>
        <li><%= link_to "Projects", projects_path %></li><hr>
        <li><%= link_to "News",  scraps_path %></li><hr>
        <li><%= link_to "Companies", companies_path %></li><hr>
        <li><%= link_to "Subsea Service Companies",  services_path %></li><hr>
        <li><%= link_to "Vessels Info",  vessels_path %></li><hr>
      <h3>Queries</h3>
        <li><%= link_to "1. Offshore Fields count by Current Operator", queries_query1_path %></li><hr>
        <li><%= link_to "2. How many fields an operating company have", queries_query2_path %></li><hr>
        <li><%= link_to "4. Contracts related to a certain project", queries_query4_path %></li><hr>
        <li><%= link_to "5. Fields where a certain stakeholder have interests in", queries_query5_path %></li><hr>
        <li><%= link_to "6. Operators connected to a stakeholder", queries_query6_path %></li><hr>
        <!-- <li><%= link_to "7. Which UKCS fields are less than 300m deep", queries_query7_path %></li> -->
        <li><%= link_to "10. Company News", queries_query10_path %></li><hr>
        <li><%= link_to "12. Latest Operating Company News", queries_query12_path %></li><hr>
        <!-- <li><%= link_to "What contracts have been awarded to Service company", queries_query8_path %></li>
        <li><%= link_to "Projects", queries_project_path %></li> -->
    </ul>
  </nav>

app/views/static_pages/home.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>﻿

<div class='ak'>
  <h2><font color="#5B5D62"><b>Welcome to <b><font color="#00B4E4"><b>Archer Knight<b></font></a></h2>
</div>

<div class='carouselak'>
  <div class='col-md-10'>

      <div id = "mycarousel" class = "carousel slide" data-ride="carousel">
          <ol class = "carousel-indicators">
            <li data-target = "#mycarousel" data-slide-to = "1" class = "active"></li>
            <li data-target = "#mycarousel" data-slide-to = "0"></li>
          </ol>

          <div class = "carousel-inner">

            <div class = "item active">
                <%= image_tag("ak1.jpg",  alt: "ak2", class:"img_responsive") %>
            </div>

            <div class = "item">
                <%= image_tag("ak2.jpg",  alt: "ak1", class:"img_responsive") %>
            </div>
          </div>

          <a class = "carousel-control left" href = "#mycarousel" data-slide = "prev">
            <span class = "icon-prev"> </span>
          </a>
          <a class = "carousel-control right" href = "#mycarousel" data-slide = "next">
            <span class = "icon-next"> </span>
          </a>

    </div>
  </div>

  <div class='col-md-2'>
    <div class = "oilprice">
      <div class="transbox">
        <script type="text/javascript" src="http://oilprice.com/widgets/crude/crudechart.js"></script>
        <noscript>Please Enable Javascript for this <a href="http://oilprice.com/">Oil Price</a> widget to work</noscript>
      </div>
    </div>
  </div>

</div>

<div class = 'col-md-10'>
    <div class ="ticker">
      <marquee><font color="#00B4E4"><b>Assisting energy sector companies grow and internationalise.<b></font></marquee>
    </div>
</div>

<div class='col-md-2'>

</div>

app/views/static_pages/ourvalues.html.erb
<h1>About Us</h1>

  <h4> We are passionate about value. At Archer Knight we know that our success is solely based
          on delivering services that enhance and effect our client's strategic growth. To that end our
          core provision focuses on a three stage system aimed at ensuring we are providing the necessary checks
          and balances required to sustain the required levels of confident investment.</h4>
<h3 style="color: #00B4E4">BE HONEST</h3>

<h4>We will be honest with all our staff, clients and suppliers and treat them with the utmost integrity. </h4>

<h3 style="color: #00B4E4">BE FAIR</h3>

<h4>We will always execute our services in the most mutually beneficial way possible. </h4>

<h3 style="color: #00B4E4">BE GOOD</h3>

<h4>We will always strive to be the leader in our sector and the best sum of our parts.</h4>

<h3 style="color: #00B4E4">BE THERE</h3>

<h4>We will engage with our clients at any time on a global basis throughout the life of contract.</h4>

</div>

app/views/static_pages/rak.html.erb
<h1>R.A.K 4</h1>

<h3 style="color:#00B4E4">What is it?</h3>
<h4>Reconnaissance AK4 (r.a.k.4), is an innovative software focused on gathering web-based patterns, trends, associations and behaviours throughout the energy sector and applying the analytical findings to our clients’ strategy documents in real time.</h4>

<h3 style="color:#00B4E4">Why is it needed?</h3>
<h4>The global subsea industry is composed of thousands of moving parts and entities, such as Operators, Supply Chain, Service Providers, Contracts, Projects, Assets, People and Infrastructure.  It can be difficult to understand how each of these interact in the wider market context.</h4>
<h3 style="color:#00B4E4">How good is it?</h3>
<h4><li>This resource provides greater efficiency than a one-off report.</h4>
<h4><li>Delivers a real-time view of the market – highlighting key developments and relationships pivotal to client strategies.</h4>
<h4><li>Allows users to conduct their own trend analysis.</h4>

app/views/static_pages/scrap_project.html.erb
<h1>Reddit's Front Page</h1>
<% @entriesArray.each do |entry| %>
  <p><%= entry.title %></p>
  <p><%= entry.link %></p>
<% end %>

app/views/static_pages/service.html.erb
<h1>Services</h1>

 <h3 style="color: #00B4E4">DIVING</h3>
  <p>Our expert has over 30 years’ industry experience working for major and independent operators as a diving technical authority and subsea technical
     engineering authority. We can provide the following services:     Technical Authority Processes & Procedures - Audits - Technical Audits - Safety Management System Audits - Medical Audits - FMECA - CPD - IMCA
    Membership Assistance - Client Representation. For more details on this service email info@archerknight.com</p>
 <h3 style="color: #00B4E4">BUSINESS DEVELOPMENT</h3>
    <p>Our expert has over 30 years’ industry experience working for major offshore contractors in commercial, tendering and business development roles. </p>
 <h3 style="color: #00B4E4">HSEQ</h3>
    <p>Our expert has over 30 years’ experience in Health and Safety, Engineering, Quality and Risk management working for subsea and commissioning
     contractors.</p>
 <h3 style="color: #00B4E4">COMMERCIAL</h3>
    <p>Our expert has over 30 years’ experience in senior commercial positions with operators and contractors, throughout the UKCS and globally.</p>
 <h3 style="color: #00B4E4">ROV</h3>
     <p>Our expert has over 25 years’ experience in ROV and ROVSV senior project direction, management and execution throughout the UKCS and globally.
    Further details on all the above mentioned facets are available upon request. info@archerknight.com</p>

app/views/static_pages/visitus.html.erb
<!-- <FORM><INPUT Type="button" VALUE="Back" onClick="history.go(-1);return true;"></FORM> -->

<h1>Visit Us</h1>

	<div class='visitus'>
		<div class ='col-md-4'>
		</div>

		<div class ='col-md-2'>
			<h3>7 Carden Place<br>
			Aberdeen<br>
			AB10 1PP</h3>
		</div>

		<!-- Google Map -->

			<div class ='col-md-5'>
				<div id="map">
					<script>
					function initMap() {
						var uluru = {lat: 57.1446107, lng: -2.1213499};
						var map = new google.maps.Map(document.getElementById('map'), {
							zoom: 14,
							center: uluru
						});
						var marker = new google.maps.Marker({
							position: uluru,
							map: map
						});
					}
				</script>
				<script async defer
					src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyNk4-Hij-eckCVwxdp9kDbqKp6FQN4Js&callback=initMap">
				</script>

				<div class ='col-md-1'>
				</div>
			</div>
		</div>
	</div>