config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  # SIMPLE ROUTES FOR APP>VIWES>PASSWORD_RESET
  get 'password_resets/new'
  get 'password_resets/edit'

  # SIMPLE ROUTES FOR APP>VIEWS>USERS
  get 'users/new'
  get 'users/dashboard'
  get 'users/show'
  get 'users/index'

  # SIMPLE ROUTES FOR APP>VIEWS>REGISTER
  get  '/register',  to: 'users#new'
  post '/register',  to: 'users#create'

  # SIMPLE ROUTES FOR APP>VIEWS>LOGIN AND APP>VIEWS>LOGOUT
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # SIMPLE ROUTES FOR APP>VIEWS>SESSION
  get 'sessions/new'

  # SIMPLE ROUTES FOR APP>VIEWS>SCRAPS
  get 'scraps/index'

  # ROUTES TO SHOW APP>VIEWS>STATIC_PAGES ERB FILES
  get 'static_pages/home'
  get 'static_pages/data_tables'
  get 'static_pages/contact'
  get 'static_pages/ourvalues'
  get 'static_pages/AKL'
  get 'static_pages/rak'
  get 'static_pages/service'
  get 'static_pages/about'
  get 'static_pages/visitus'
  get 'static_pages/scrap_project'

  # RESOURCEFUL ROUTES
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :operatings,    :index, :show, :new, :create, :destroy
  resources :services,      :index, :show, :new, :create, :destroy
  resources :news,          :index, :show, :destroy
  resources :scraps,        :index, :show, :new, :create, :destroy
  resources :locations,     :index, :show, :new, :create, :destroy
  resources :employees,     :index, :show, :new, :create, :destroy
  resources :vessels,       :index
  resources :items,         :index, :show, :new, :create, :destroy
  resources :offshores,     :index, :show, :new, :create, :destroy
  resources :projects,      :index, :show, :new, :create, :destroy
  resources :contracts,     :index, :show, :new, :create, :destroy
  resources :companies,     :index, :show, :new, :create, :destroy
  resources :users
  resources :tests
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # ROUTES TO SHOW EACH OF THE QUERIES ERB VIEW:
  get 'queries/query1', to: 'queries#query1'
  get 'queries/query2', to: 'queries#query2'
  get 'queries/query4', to: 'queries#query4'
  get 'queries/query5', to: 'queries#query5'
  get 'queries/query6', to: 'queries#query6'
  get 'queries/query7', to: 'queries#query7'
  get 'queries/query8', to: 'queries#query8'
  get 'queries/query10', to: 'queries#query10'
  get 'queries/query12', to: 'queries#query12'
  get 'queries/project', to: 'queries#project'
  # ROUTES TO PROCESS THE FORM IN EACH OF THE QUERIES ERB VIEW
  post 'queries/query1'
  post 'queries/query2'
  post 'queries/query4'
  post 'queries/query5'
  post 'queries/query6'
  post 'queries/query7'
  post 'queries/query8'
  post 'queries/query10'
  post 'queries/query12'
  post 'queries/project'

end

app/models/employee.rb
class Employee < ApplicationRecord
    
    default_scope -> { order(created_at: :asc) }
    
    validates :full_name, presence: true
    validates :current_company, presence: true
    validates :country, presence: true
    validates :position, presence: true
    validates :ak_notes, presence: true
    validates :classification, presence: true
   
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
          before_action :require_login, only: [:index, :new, :edit, :update, :destroy], raise: false
        
        
        #showing all record in the comploey table
        def index
           @workers = Employee.all.paginate(page: params[:page], :per_page => 70) 
        end
                
             
         #display a single record from the employee table      
        def show
          @workers = Employee.find(params[:id])
        end
        
        
         
         #display the employee form 
        def new
            @workers  = Employee.new
        end
        
        
        
         #saving a new employee a record 
        def create
           @workers = Employee.new(my_worker)
        if   @workers.save
            flash[:success] = "A record has been successfully added"
        redirect_to employees_path
        else
          render 'new'
        end
        end
    
        
          #strong parameters
        def my_worker
            params.require(:employee).permit(:full_name, :current_company, :country, :position, :ak_notes, :classification,   )
              
        end
        
        
        
          #edit employee table 
         def edit
            @workers = Employee.find(params[:id])
            
         end
         
         
         
         #upadat the employe table 
         def update
            @workers = Employee.find(params[:id])
            if @workers.update_attributes(my_worker)
               flash[:success] = "People form updated"
               redirect_to employees_path
            else
              render'edit'
            end
         end
        
        
        
          # delete a particular employee form 
        def destroy
            Employee.find(params[:id]).destroy
            flash[:success] = "A record has been successfully deleted"
              redirect_to employees_path
     
        end 
        
        
        
        
           #security feature
         def require_login
            unless logged_in?
              flash[:danger] = "You must login to access this page"
              redirect_to login_path 
            end
        end
        
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
 <%= form_for  @workers  do |f| %>
      
      <div class="row">
        <%= render 'shared/error_message', object: @workers%>
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :Full_name%><font color="red">*</font>
         <%= f.text_field  :full_name,  class: 'form-control' %> 
         
       </div>
       
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :current_Company%><font color="red">*</font>
         <%= f.text_field  :current_company, class: 'form-control' %> 
         
        </div>
       
        <div class="col-md-6 col-md-offset-2">
         <%= f.label :current_country%><font color="red">*</font>
         <%= f.text_field  :country, class: 'form-control' %> 
         
        </div> 
      

       <div class="col-md-6 col-md-offset-2">
         <%= f.label :Company_type%><font color="red">*</font>
         <%= f.text_field  :position , class: 'form-control' %><br>
         
       </div>
       
       
       
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :AK_notes%><font color="red">*</font>
         <%= f.text_field  :ak_notes, class: 'form-control' %> 
         
       </div>
   
       
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :Classification%><font color="red">*</font>
         <%= f.text_field  :classification , class: 'form-control' %><br>
         
       </div>
       
       
      
       
       
   
        
     
       </div>
       <br>
      <div class="col-md-5 col-md-offset-2">
      <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
    
   

app/views/employees/edit.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables", static_pages_data_tables_path %></li>
  <li><%= link_to "View all employees", employees_path %></li>
</ul>
</nav>
<center><h3>Add new employee</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'employees/form' %>
    <br>
     </div>
  </div>
  </div>
 
 
  

app/views/employees/index.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables",  static_pages_data_tables_path %></li>
  <li><%= link_to "Add new Employee", new_employee_path  %></li>
</ul>
</nav>
              
                      
<div class="page-header"><h3>Company People</h3></div>
<div class="span3">
<table align="" border="1px" class="table table-striped">
      <th>Full Name</th>
       <th>Current Company</th>
        <th>Country</th>
         <th>Position</th>
           <th>Ak_Notes</th>
            <th>Classification</th>
             <th>Edit</th>
               <th>Delete</th>
       <% @workers.each do |worker| %>
      <tr><td><%= worker.full_name%></td>
            <td><%= worker.current_company %></td>
              <td><%= worker.country %></td>
               <td><%= worker.position %></td>
                  <td><%= worker.ak_notes%></td>
                    <td><%=worker.classification%></td>
  
              
             
              
            
           <% if current_user.admin? %>     
             <td><%= link_to "Edit", edit_employee_path(worker),data: { confirm: " Are you Sure you want to edit?" }   %></td>
              <td><%= link_to "Delete", employee_path(worker), method: :delete,
              data: { confirm: " Are You sure you want to Delete?" } %></td></tr>  
           <% end %>
           <% end %>
    </table>
</div>
</div>

app/views/employees/new.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables", static_pages_data_tables_path %></li>
</ul>
</nav>
<center><h3>Add new person</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'employees/form' %>
    <br>
     </div>
  </div>
  </div>
 
 
  

app/views/employees/show.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "Home",  static_pages_data_tables_path %></li>
  <li><%= link_to "Add new person", new_employee_path  %></li>
</ul>
</nav>
              
                      
<div class="page-header"><h3>Company People</h3></div>
<div class="span3">
<table align="" border="1px" class="table table-striped">
   <th>Full Name</th>
    <th>Current company</th>
     <th>Country</th>
      <th>position</th>
        <th>Ak_Notes</th>
          <th>Classification</th>
          <th>Edit</th>
         <th>Delete</th>

 
   <tr><td><%= @workers.full_name%></td>
         <td><%= @workers.current_company %></td>
           <td><%= @workers.country %></td>
            <td><%= @workers.position %></td>
               <td><%= @workers.ak_notes%></td>
                 <td><%= @workers.classification%></td>
           
          
           
            
                
         <td><%= link_to "Edit", edit_employee_path(@workers),data: { confirm: " Are you Sure you want to edit?" }   %></td>
          <td><%= link_to "Delete", employee_path(@workers), method: :delete,
          data: { confirm: " Are You sure you want to Delete?" } %></td></tr>   

    </table>
</div>