config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  # SIMPLE ROUTES FOR APP>VIWES>PASSWORD_RESET
  get 'password_resets/new'
  get 'password_resets/edit'

  # SIMPLE ROUTES FOR APP>VIEWS>USERS
  get 'users/new'
  get 'users/dashboard'
  get 'users/show'
  get 'users/index'

  # SIMPLE ROUTES FOR APP>VIEWS>REGISTER
  get  '/register',  to: 'users#new'
  post '/register',  to: 'users#create'

  # SIMPLE ROUTES FOR APP>VIEWS>LOGIN AND APP>VIEWS>LOGOUT
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # SIMPLE ROUTES FOR APP>VIEWS>SESSION
  get 'sessions/new'

  # SIMPLE ROUTES FOR APP>VIEWS>SCRAPS
  get 'scraps/index'

  # ROUTES TO SHOW APP>VIEWS>STATIC_PAGES ERB FILES
  get 'static_pages/home'
  get 'static_pages/data_tables'
  get 'static_pages/contact'
  get 'static_pages/ourvalues'
  get 'static_pages/AKL'
  get 'static_pages/rak'
  get 'static_pages/service'
  get 'static_pages/about'
  get 'static_pages/visitus'
  get 'static_pages/scrap_project'

  # RESOURCEFUL ROUTES
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :operatings,    :index, :show, :new, :create, :destroy
  resources :services,      :index, :show, :new, :create, :destroy
  resources :news,          :index, :show, :destroy
  resources :scraps,        :index, :show, :new, :create, :destroy
  resources :locations,     :index, :show, :new, :create, :destroy
  resources :employees,     :index, :show, :new, :create, :destroy
  resources :vessels,       :index
  resources :items,         :index, :show, :new, :create, :destroy
  resources :offshores,     :index, :show, :new, :create, :destroy
  resources :projects,      :index, :show, :new, :create, :destroy
  resources :contracts,     :index, :show, :new, :create, :destroy
  resources :companies,     :index, :show, :new, :create, :destroy
  resources :users
  resources :tests
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # ROUTES TO SHOW EACH OF THE QUERIES ERB VIEW:
  get 'queries/query1', to: 'queries#query1'
  get 'queries/query2', to: 'queries#query2'
  get 'queries/query4', to: 'queries#query4'
  get 'queries/query5', to: 'queries#query5'
  get 'queries/query6', to: 'queries#query6'
  get 'queries/query7', to: 'queries#query7'
  get 'queries/query8', to: 'queries#query8'
  get 'queries/query10', to: 'queries#query10'
  get 'queries/query12', to: 'queries#query12'
  get 'queries/project', to: 'queries#project'
  # ROUTES TO PROCESS THE FORM IN EACH OF THE QUERIES ERB VIEW
  post 'queries/query1'
  post 'queries/query2'
  post 'queries/query4'
  post 'queries/query5'
  post 'queries/query6'
  post 'queries/query7'
  post 'queries/query8'
  post 'queries/query10'
  post 'queries/query12'
  post 'queries/project'

end

app/models/company.rb
class Company < ApplicationRecord
    
     default_scope -> { order(created_at: :asc) }
     has_many :offshores
     



     
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

        before_action :require_login, only: [:index, :edit, :update, :destroy], raise: false
       #showing all record in the campany table
        def index
          @company = Company.all.paginate(page: params[:page], :per_page => 70)
        end


        #showing single reecord in the company table
        def show
          @comanay = Company.find(params[:id])
        end



        #display input form of the campany table
        def new
          @company = Company.new
        end



         #saving a new record to the company table
        def create
             @company = Company.new(comy)
            if  @company.save
                flash[:success] = "A record has been successfully added"
            redirect_to companies_path
            else
              render 'new'
            end
        end



         #strong parameters
        def comy
        params.require(:company).permit(:company_name, :company_type)
        end



         # editing  a record the compay table
         def edit
            @company = Company.find(params[:id])
         end



         #upadat a record in the comapy table
          def update
            @company = Company.find(params[:id])
            if  @location.update_attributes(located)
               flash[:success] = "Location form updated"
               redirect_to companies_path
            else
                render'edit'
            end
          end



        #deleting a record from company table
        def destroy
            Company.find(params[:id]).destroy
            flash[:success] = "A record has been successfully deleted"
            redirect_to companies_path
        end


        #security feature
         def require_login
            unless logged_in?
              flash[:danger] = "You must login to access this page"
              redirect_to login_path
            end
         end
    
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
 <%= form_for  @company  do |f| %>
      
      <div class="row">
       
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :company_name%><font color="red">*</font>
         <%= f.text_field  :company_name,  class: 'form-control' %><br>
         
       </div>
      
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :company_type%><font color="red">*</font>
         <%= f.select  :company_type, ["Service company", "Operating Company"], class: 'form-control' %> 
         
        </div>
       
       </div>
       <br>
      <div class="col-md-5 col-md-offset-2">
      <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
<% end %>
    
   

app/views/companies/edit.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables", static_pages_data_tables_path %></li>
  <li><%= link_to "View all employees", employees_path %></li>
</ul>
</nav>
<center><h3>Add new employee</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'companies/form' %>
    <br>
     </div>
  </div>
  </div>
 
 
  

app/views/companies/index.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables",  static_pages_data_tables_path %></li>
  <li><%= link_to "Add new company", new_company_path  %></li>
</ul>
</nav>
              
                      
<div class="page-header"><h3>Company People</h3></div>
<div class="span3">
<table align="" border="1px" class="table table-striped">
   <th>Company Name</th>
    <th>Company Type</th>
        <th>Edit</th>
           <th>Delete</th>
           
  <% @company.each do |row| %>
 
   <tr><td><%= row.company_name%></td>
         <td><%= row.company_type%></td>
        
          <% if current_user.admin? %>
          <td><%= link_to "Edit", edit_company_path(row),data: { confirm: " Are you Sure you want to edit?" }   %></td>
          <td><%= link_to "Delete", company_path(row), method: :delete,
          data: { confirm: " Are You sure you want to Delete?" } %></td></tr>
           <% end %>
 <% end %>
    </table>
</div>
</div>

app/views/companies/new.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables", static_pages_data_tables_path %></li>
</ul>
</nav>
<center><h3>Add new company</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'companies/form' %>
    <br>
     </div>
  </div>
  </div>
 
 
  