config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  # SIMPLE ROUTES FOR APP>VIWES>PASSWORD_RESET
  get 'password_resets/new'
  get 'password_resets/edit'

  # SIMPLE ROUTES FOR APP>VIEWS>USERS
  get 'users/new'
  get 'users/dashboard'
  get 'users/show'
  get 'users/index'

  # SIMPLE ROUTES FOR APP>VIEWS>REGISTER
  get  '/register',  to: 'users#new'
  post '/register',  to: 'users#create'

  # SIMPLE ROUTES FOR APP>VIEWS>LOGIN AND APP>VIEWS>LOGOUT
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # SIMPLE ROUTES FOR APP>VIEWS>SESSION
  get 'sessions/new'

  # SIMPLE ROUTES FOR APP>VIEWS>SCRAPS
  get 'scraps/index'

  # ROUTES TO SHOW APP>VIEWS>STATIC_PAGES ERB FILES
  get 'static_pages/home'
  get 'static_pages/data_tables'
  get 'static_pages/contact'
  get 'static_pages/ourvalues'
  get 'static_pages/AKL'
  get 'static_pages/rak'
  get 'static_pages/service'
  get 'static_pages/about'
  get 'static_pages/visitus'
  get 'static_pages/scrap_project'

  # RESOURCEFUL ROUTES
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :operatings,    :index, :show, :new, :create, :destroy
  resources :services,      :index, :show, :new, :create, :destroy
  resources :news,          :index, :show, :destroy
  resources :scraps,        :index, :show, :new, :create, :destroy
  resources :locations,     :index, :show, :new, :create, :destroy
  resources :employees,     :index, :show, :new, :create, :destroy
  resources :vessels,       :index
  resources :items,         :index, :show, :new, :create, :destroy
  resources :offshores,     :index, :show, :new, :create, :destroy
  resources :projects,      :index, :show, :new, :create, :destroy
  resources :contracts,     :index, :show, :new, :create, :destroy
  resources :companies,     :index, :show, :new, :create, :destroy
  resources :users
  resources :tests
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # ROUTES TO SHOW EACH OF THE QUERIES ERB VIEW:
  get 'queries/query1', to: 'queries#query1'
  get 'queries/query2', to: 'queries#query2'
  get 'queries/query4', to: 'queries#query4'
  get 'queries/query5', to: 'queries#query5'
  get 'queries/query6', to: 'queries#query6'
  get 'queries/query7', to: 'queries#query7'
  get 'queries/query8', to: 'queries#query8'
  get 'queries/query10', to: 'queries#query10'
  get 'queries/query12', to: 'queries#query12'
  get 'queries/project', to: 'queries#project'
  # ROUTES TO PROCESS THE FORM IN EACH OF THE QUERIES ERB VIEW
  post 'queries/query1'
  post 'queries/query2'
  post 'queries/query4'
  post 'queries/query5'
  post 'queries/query6'
  post 'queries/query7'
  post 'queries/query8'
  post 'queries/query10'
  post 'queries/query12'
  post 'queries/project'

end

app/models/item.rb
class Item < ApplicationRecord
   belongs_to :location, :optional => true
   default_scope -> { order(created_at: :asc) }
   
    validates :item_name, presence: true
    validates :item_type, presence: true
    validates :item_owner, presence: true
    validates :current_manager, presence: true
    validates :previous_manager, presence: true
    validates :item_specifications, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
        before_action :require_login, only: [:index, :edit, :update, :destroy], raise: false
        #showing all record in the campany table
        def index
         @asset=Item.all.paginate(page: params[:page], :per_page => 70)
        end


         #displaying a single record in the Item table
        def show
           @asset = Item.find(params[:id])
        end

         #display asset table
        def new
           @asset = Item.new
        end

        # adding a record in the asset table
        def create
              @asset = Item.new(details)
            if  @asset.save
                flash[:success] = "A record has been successfully added"
            redirect_to items_path
            else
              render 'new'
            end
        end

       #editing  record in the asset table

         def edit
            @asset  = Item.find(params[:id])
         end


        #upadat record in the asset table
         def update
            @asset = Item.find(params[:id])
            if @asset.update_attributes(details)
               flash[:success] = "Asset Form updated"
               redirect_to items_path
            else
               render'edit'
            end
         end


        #strong parameters
        def details
           params.require(:item).permit(:item_name, :item_type, :item_owner,  :current_manager, :previous_manager, :item_specifications)
        end


         #deleting a record from the campany table
        def destroy
            Item.find(params[:id]).destroy
            flash[:success] = "A record has been successfully deleted"
               redirect_to items_path
        end
         #security feature
         def require_login
            unless logged_in?
              flash[:danger] = "You must login to access this page"
              redirect_to login_path
            end
        end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
 <%= form_for  @asset  do |f| %>
      <div class="row">
        <%= render 'shared/error_message', object: @asset%>
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :Asset_name%><font color="red">*</font>
         <%= f.text_field  :item_name,  class: 'form-control' %> 
       </div>
       
       
       <div class="col-md-6 col-md-offset-2">
         <%= f.label :Asset_type=%><font color="red">*</font>
         <%= f.text_field  :item_type, class: 'form-control' %> 
       </div>
       
        <div class="col-md-6 col-md-offset-2">
         <%= f.label :Asset_owner=%><font color="red">*</font>
         <%= f.text_field  :item_owner, class: 'form-control' %> 
       </div>
       
       
       
        <div class="col-md-6 col-md-offset-2">
         <%= f.label :Current_manager=%><font color="red">*</font>
         <%= f.text_field  :current_manager, class: 'form-control' %> 
         
       </div>
       
       
        <div class="col-md-6 col-md-offset-2">
         <%= f.label :Previous_manager=%><font color="red">*</font>
         <%= f.text_field  :previous_manager, class: 'form-control' %> 
         
       </div>
       
       
        <div class="col-md-6 col-md-offset-2">
         <%= f.label :Asset_specifications=%><font color="red">*</font>
         <%= f.text_field  :item_specifications , class: 'form-control' %> 
         
       </div>
       
       
       </div>
       <br>
      <div class="col-md-5 col-md-offset-2">
      <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>

app/views/items/edit.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables",   static_pages_data_tables_path %></li>
  <li><%= link_to "View Assets", items_path  %></li>
</ul>
</nav>
<center><h3>Edit Asset table</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'items/form' %>
    <br>
  </div>  
</div>
</div>
  

app/views/items/index.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables",   static_pages_data_tables_path %></li>
  <li><%= link_to "Add new asset", new_item_path  %></li>
   <li><%= link_to " Vessels Information", vessels_path  %></li>
</ul>
</nav>
              
                      
<div class="page-header"><h3>Assets</h3></div>
<div class="span3"> 
<table align="" border="1px"  cellspacing="5px" class="table table-striped">
   <th>Asset Name</th>
    <th>Asset Type</th>
     <th>Asset Owner</th>
       <th>Current Manager</th>
        <th>Previous Manager</th>
         <th>Asset Specification</th>
          <th>Edit</th>
           <th>Delete</th>

<% @asset.each do |row| %>
 
   <tr><td><%= row.item_name%></td>
       <td><%= row.item_type%></td>
        <td><%= row.item_owner%></td>
           <td><%= row.current_manager%></td>
            <td><%= row.previous_manager%></td>
             <td><%= row.item_specifications%></td>
             
          <% if current_user.admin? %>
           <td><%= link_to "Edit", edit_item_path(row),data: { confirm: " Are you Sure you want to edit?" }   %></td>
          <td><%= link_to "Delete", item_path(row), method: :delete,
          data: { confirm: " Are You sure you want to Delete?" } %></td></tr> 
          <% end %>
 <% end %>
    </table>
    
</div>
</div>

app/views/items/new.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "All data tables",   static_pages_data_tables_path %></li>
  <li><%= link_to "View Assets", items_path  %></li>
  
</ul>
</nav>
<center><h3>Add new asset</h3></center>

<center><font color="red">All fields marked * are required fields</font></center>
<div class="row">
    
  <div class="col-md-8 col-md-offset-3">
     
     <%= render 'items/form' %>
    <br>
    </div>
   </div>  
  </div>
  
  

app/views/items/show.html.erb
<div class="container">
<nav>
<ul class="breadcrumb">
  <li><%= link_to "Home",   static_pages_data_tables_path %></li>
  <li><%= link_to "Add new asset", new_item_path  %></li>
   <li><%= link_to "Vessels Information",vessels_path  %></li>
</ul>
</nav>
              
                      
<div class="page-header"><h3>Assets</h3></div>
<div class="span3"> 
<table align="" border="1px"  cellspacing="5px" class="table table-striped">
   <th>Asset Name</th>
    <th>Asset Type</th>
     <th>Asset Owner</th>
       <th>Current Manager</th>
        <th>Previous Manager</th>
         <th>Asset Specification</th>
          <th>Edit</th>
           <th>Delete</th>

 
   <tr><td><%= @asset.assets_name%></td>
       <td><%= @asset.asset_type%></td>
        <td><%= @asset.asset_owner%></td>
           <td><%= @asset.current_manager%></td>
            <td><%= @asset.previous_manager%></td>
             <td><%= @asset.asset_specifications%></td>

           <td><%= link_to "Edit", edit_item_path(@asset),data: { confirm: " Are you Sure you want to edit?" }   %></td>
          <td><%= link_to "Delete", item_path(@asset), method: :delete,
          data: { confirm: " Are You sure you want to Delete?" } %></td></tr> 
          

    </table>
    
</div>
</div>